services:
   postgres:
      container_name: postgres
      image: postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 1234
         PGDATA: /data/postgres
      volumes:
      - postgres:/data/postgres
      ports:
      - 5432:5432
      networks:
      - postgres
      restart: unless-stopped

networks:
   postgres:
      driver: bridge

volumes:
   postgres: null
   pgadmin: null